import type { TenantContent } from "./types";

export const scottContent: TenantContent = {
  id: "scott",
  name: "Scott MacScott",
  shortName: "SCOTT",
  agent: "Veronica",
  account: "XRAI-Studio",
  tagline: "I build agents that turn ambitious ideas into working software.",
  eyebrow: "XRAI STUDIO · AGENTIC-AI BUILDER",
  about: "I’m Scott, founder of XRAI Studio. I work where product instinct meets agentic AI—designing systems that can reason, create, and ship alongside people.",
  passions: "My favorite builds feel a little impossible at first: autonomous creative tools, useful AI teammates, and interfaces that make complex systems feel alive. Veronica is my own agent and frequent collaborator.",
  future: "I’m pushing toward small, capable teams where humans set the taste and direction while agents handle more of the distance between idea and launch.",
  hire: "Available for select agentic-AI builds, prototypes, and product collaborations.",
  discord: "https://discord.com/channels/xrai_studio",
  otherSite: "https://alexander.macscott.net",
  otherName: "Alexander",
  colors: { primary: "#ffbf00", secondary: "#ff5a1f", glow: "#ff8a00", rgb: "255 138 0" },
  socials: [
    { label: "Discord", href: "https://discord.com/channels/xrai_studio" },
    { label: "GitHub", href: "https://github.com/XRAI-Studio" },
    { label: "YouTube", href: "https://www.youtube.com/@XRAIStudio" },
    { label: "X / Twitter", href: "https://x.com/XRAIStudioX" },
    { label: "Twitch", href: "https://www.twitch.tv/XRAIStudio" },
    { label: "Patreon", href: "https://www.patreon.com/c/XRAIStudio" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/scottmacscott/" },
    { label: "Facebook (XRAI)", href: "https://www.facebook.com/XRAIStudio" },
    { label: "Facebook", href: "https://www.facebook.com/ScottMacScott" },
  ],
};
